openapi: "3.0.0"
info:
  version: 1.0.0
  title: MOVI_IO API
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  #OAUTH ENDPOINTS
  /oauth/login:
    post:
      tags:
          - oauth
      summary: usuario faz login e retorna token
  /oauth/forgot_password:
    post:
      tags:
        - oauth
      summary: usuario esqueceu a senha
  /oauth/signin:
    post:
      tags:
        - oauth
      summary: usuario vai criar uma nova conta
  /oauth/refresh-token:
    post:
      tags:
        - oauth
      summary: refresh token do usuario
  /oauth/token:
    get:
      tags:
        - oauth
      summary: teste de api token
      security:
        - bearerAuth: []
  
  # LIST ENDPOINTS
  /list:
    post:
      security:
        - bearerAuth: []
      tags:
        - list
      summary: usuario logado cria uma nova lista
    get:
      tags:
        - list
      summary: retorna todas as listas criadas pelo usuario logado
      security:
        - bearerAuth: []
  /list/{listId}:
    put:
      tags:
          - list
          - listById
      summary: edita uma lista 
    get:
      tags:
        - list
        - listById
      summary: retorna uma lista
    delete:
      tags:
        - list
        - listById
      summary: apaga uma lista

components:
  securitySchema:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: jwt